<a href="https://colab.research.google.com/github/tithi-123/Brain-Tumour-/blob/main/braintumer_finalans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

features_list=np.load("/content/drive/My Drive/feature_file1.npy")
print(features_list)
print(len(features_list))

[[1.37170147 0.26096868 0.78693916 ... 0.70228307 0.95478001 1.        ]
 [0.91868349 0.28453324 0.81256106 ... 0.82737737 0.58164642 1.        ]
 [1.04408482 0.25125549 0.79574423 ... 0.78288225 0.72246343 1.        ]
 ...
 [1.02206534 0.09591271 0.7340418  ... 0.641435   1.0812317  3.        ]
 [1.79636949 0.07668119 0.67446671 ... 0.54620163 1.35493425 3.        ]
 [0.91193738 0.1167889  0.7663657  ... 0.67863917 0.99337252 3.        ]]
3064


In [ ]:
!pip install -q pydicom

In [ ]:
import matplotlib.pyplot as plt
import os
import pydicom
import numpy as np 
import skimage.io
import skimage.feature
from scipy import ndimage, misc 
from sklearn.cluster import KMeans

from pathlib import Path
import numpy as np
import h5py
import matplotlib.pyplot as plt
import pandas as pd

from skimage.filters import roberts,sobel,scharr,prewitt

import cv2


In [ ]:
from scipy import ndimage as nd
from skimage.feature import local_binary_pattern
from skimage.filters import gabor
import pandas as pd

In [ ]:
feature_df=pd.DataFrame(features_list,columns=['contrast','energy','homogeneity','correlation','dissimilarity','ASM','lbp_energy','lbp_entropy','gabor_energy','gabor_entropy','label'])
feature_df1=feature_df.fillna(0)
print(feature_df.fillna(0))

      contrast    energy  homogeneity  ...  gabor_energy  gabor_entropy  label
0     1.371701  0.260969     0.786939  ...      0.702283       0.954780    1.0
1     0.918683  0.284533     0.812561  ...      0.827377       0.581646    1.0
2     1.044085  0.251255     0.795744  ...      0.782882       0.722463    1.0
3     1.283146  0.347080     0.809181  ...      0.749144       0.848199    1.0
4     1.287427  0.248243     0.781301  ...      0.732454       0.842323    1.0
...        ...       ...          ...  ...           ...            ...    ...
3059  0.975597  0.090099     0.732711  ...      0.682484       0.984974    3.0
3060  1.153716  0.150458     0.781524  ...      0.739621       0.847404    3.0
3061  1.022065  0.095913     0.734042  ...      0.641435       1.081232    3.0
3062  1.796369  0.076681     0.674467  ...      0.546202       1.354934    3.0
3063  0.911937  0.116789     0.766366  ...      0.678639       0.993373    3.0

[3064 rows x 11 columns]


svm

In [ ]:
Y=feature_df1['label'].values

X=feature_df1.drop(labels = ['label'], axis=1)

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=20)

from sklearn.svm import LinearSVC

model=LinearSVC(max_iter=1000)

model.fit(X_train,Y_train)
prediction_test=model.predict(X_test)
from sklearn import metrics
print("accuracy = ",metrics.accuracy_score(Y_test,prediction_test))

accuracy =  0.6704730831973899


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
print('accuracy_score',accuracy_score(Y_test,prediction_test))
print('precision_score',precision_score(Y_test,prediction_test,average=None))
print('recall_score',recall_score(Y_test,prediction_test,average=None))
print('f1_score',f1_score(Y_test,prediction_test,average=None))
print('confusion_matrix',confusion_matrix(Y_test,prediction_test))

accuracy_score 0.6704730831973899
precision_score [0.56818182 0.70684039 0.65208333]
recall_score [0.27573529 0.76408451 0.81088083]
f1_score [0.37128713 0.73434856 0.72286374]
confusion_matrix [[ 75 120  77]
 [ 44 434  90]
 [ 13  60 313]]


RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
Y=feature_df1['label'].values

X=feature_df1.drop(labels = ['label'], axis=1)

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=20)


In [ ]:
model1=RandomForestClassifier(n_estimators=100,random_state=42)
model1.fit(X_train,Y_train)
prediction_test=model1.predict(X_test)
from sklearn import metrics
print("accuracy = ",metrics.accuracy_score(Y_test,prediction_test))


accuracy =  0.763458401305057


In [ ]:
print('accuracy_score',accuracy_score(Y_test,prediction_test))
print('precision_score',precision_score(Y_test,prediction_test,average=None))
print('recall_score',recall_score(Y_test,prediction_test,average=None))
print('f1_score',f1_score(Y_test,prediction_test,average=None))
print('confusion_matrix',confusion_matrix(Y_test,prediction_test))

accuracy_score 0.763458401305057
precision_score [0.61044177 0.78350515 0.83037975]
recall_score [0.55882353 0.8028169  0.84974093]
f1_score [0.58349328 0.79304348 0.83994878]
confusion_matrix [[152  90  30]
 [ 75 456  37]
 [ 22  36 328]]


with k means

In [ ]:
import numpy as np
features_list_cnn=np.load("/content/drive/My Drive/feature_file_cnn.npy")

In [ ]:
feature_df_cnn=pd.DataFrame(features_list_cnn,columns=['contrast','energy','homogeneity','correlation','dissimilarity','ASM','lbp_energy','lbp_entropy','gabor_energy','gabor_entropy','label'])
feature_df1_cnn=feature_df_cnn.fillna(0)
print(feature_df_cnn.fillna(0))

      contrast    energy  homogeneity  ...  gabor_energy  gabor_entropy  label
0     1.579646  0.229679     0.778785  ...      0.702283       0.954780    1.0
1     1.061380  0.259243     0.803405  ...      0.827377       0.581646    1.0
2     1.207207  0.223041     0.788068  ...      0.782882       0.722463    1.0
3     1.450033  0.321876     0.805935  ...      0.749144       0.848199    1.0
4     1.467737  0.216545     0.774829  ...      0.732454       0.842323    1.0
...        ...       ...          ...  ...           ...            ...    ...
3059  1.112546  0.089346     0.719721  ...      0.682484       0.984974    3.0
3060  1.357407  0.159162     0.772012  ...      0.739621       0.847404    3.0
3061  1.167392  0.096328     0.722155  ...      0.641435       1.081232    3.0
3062  2.065196  0.076201     0.664179  ...      0.546202       1.354934    3.0
3063  1.042827  0.124609     0.755635  ...      0.678639       0.993373    3.0

[3064 rows x 11 columns]


In [ ]:
Y_cnn=feature_df1_cnn['label'].values

X_cnn=feature_df1_cnn.drop(labels = ['label'], axis=1)

from sklearn.model_selection import train_test_split

X_train_cnn,X_test_cnn,Y_train_cnn,Y_test_cnn = train_test_split(X_cnn,Y_cnn,test_size=0.4,random_state=20)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_cnn=RandomForestClassifier(n_estimators=1000,random_state=42)
model_cnn.fit(X_train_cnn,Y_train_cnn)
prediction_test_cnn=model_cnn.predict(X_test_cnn)
from sklearn import metrics
print("accuracy = ",metrics.accuracy_score(Y_test_cnn,prediction_test_cnn))


accuracy =  0.7495921696574225


In [ ]:
print(Y_train.shape[0])
print(Y_test.shape[0])

NameError: ignored